# Generated by Django 6.0.1 on 2026-02-05 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(blank=True, null=True, upload_to='contracts/%Y/%m/')),
                ('rfp_id', models.CharField(blank=True, max_length=255, null=True)),
                ('issuing_agency', models.CharField(max_length=255)),
                ('jurisdiction_state', models.CharField(default='CA', max_length=2)),
                ('jurisdiction_county', models.CharField(blank=True, max_length=255, null=True)),
                ('jurisdiction_city', models.CharField(blank=True, max_length=255, null=True)),
                ('required_certifications', models.JSONField(blank=True, default=list)),
                ('required_clearances', models.JSONField(blank=True, default=list)),
                ('onsite_required', models.BooleanField(blank=True, null=True)),
                ('work_locations', models.JSONField(blank=True, default=list)),
                ('naics_codes', models.JSONField(blank=True, default=list)),
                ('industry_tags', models.JSONField(blank=True, default=list)),
                ('min_past_performance', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_value_estimate', models.CharField(blank=True, max_length=255, null=True)),
                ('timeline_duration', models.CharField(blank=True, max_length=255, null=True)),
                ('work_description', models.TextField(blank=True, null=True)),
                ('award_date', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.CharField(blank=True, max_length=50, null=True)),
                ('end_date', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_contract_value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('clearances', models.JSONField(blank=True, default=list)),
                ('naics_codes', models.JSONField(blank=True, default=list)),
                ('industry_tags', models.JSONField(blank=True, default=list)),
                ('work_locations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
