"""
Django settings for civitas project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env (ignored by git).
env_path = BASE_DIR / '.env'
load_dotenv(str(env_path), override=True)


def _load_env_fallback():
    """If AWS vars still missing (e.g. runserver subprocess), read .env file directly."""
    if not env_path.exists():
        return
    want_keys = {
        'AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY', 'AWS_SESSION_TOKEN',
        'AWS_STORAGE_BUCKET_NAME', 'AWS_S3_REGION_NAME',
    }
    try:
        with open(env_path, 'r') as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith('#'):
                    continue
                if '=' in line:
                    key, _, value = line.partition('=')
                    key = key.strip()
                    value = value.strip().strip('"').strip("'")
                    if key in want_keys and value and not os.getenv(key):
                        os.environ[key] = value
    except Exception:
        pass


_load_env_fallback()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-139+z+r8*4bphs#o(%k%gvw7eki@(nq^y@)1k4)n7r3u#ni@iw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'civitas-server.onrender.com']

# Required when frontend calls Django from another origin; otherwise POST gets 403 (CSRF).
# Must include every origin that hosts the frontend (local + production).
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'http://localhost:3001',
    'http://127.0.0.1:3000',
    'http://127.0.0.1:3001',
    'https://civitas-ai.onrender.com',
]
_extra_csrf = os.getenv('CSRF_TRUSTED_ORIGINS_EXTRA', '')
if _extra_csrf:
    CSRF_TRUSTED_ORIGINS.extend(s.strip() for s in _extra_csrf.split(',') if s.strip())
# So the CSRF cookie is sent on cross-origin POST (required for Render frontend → backend)
CSRF_COOKIE_SAMESITE = 'None'
CSRF_COOKIE_SECURE = True

# Session cookie must also be sent on cross-origin requests so auth/me/ and other API calls see the logged-in user
SESSION_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SECURE = True

# NOTE: Session and CSRF are entirely handled by Django (this server), not by AWS.
# - Session: stored in Django's session backend (db or cache). The session key is in the browser cookie.
# - CSRF token: generated by Django per session. AWS is only used for profile/contracts/file storage (DynamoDB/S3).
# Account-switching issues come from the browser sending the wrong session cookie, not from Django vs AWS.

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'storages',  # S3 for uploaded files
    'contracts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'civitas.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'civitas.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# AWS: profile + contracts in DynamoDB, uploaded files in S3 (no toggles; always AWS)
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_SESSION_TOKEN = os.getenv('AWS_SESSION_TOKEN')  # optional; for temporary credentials
AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'us-east-1')
AWS_REGION = os.getenv('AWS_S3_REGION_NAME', 'us-east-1')
DYNAMODB_PROFILE_TABLE = os.getenv('DYNAMODB_PROFILE_TABLE', 'civitas-user-profiles')
DYNAMODB_CONTRACT_TABLE = os.getenv('DYNAMODB_CONTRACT_TABLE', 'civitas-contracts')

# Media: always S3
if AWS_STORAGE_BUCKET_NAME:
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
    STORAGES = {
        'default': {'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage'},
        'staticfiles': {'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage'},
    }
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/'
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
    AWS_DEFAULT_ACL = 'private'
    AWS_S3_FILE_OVERWRITE = False
else:
    MEDIA_URL = 'media/'
    MEDIA_ROOT = BASE_DIR / 'media'

# REST framework: Bearer token (AWS DynamoDB) first, then session. Token avoids cross-origin cookie issues.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'contracts.auth.BearerTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
}

# CORS - allow frontend during development
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://localhost:3001',
    'http://127.0.0.1:3000',
    'http://127.0.0.1:3001',
    'https://civitas-ai.onrender.com',
]

# Contract extraction (LLM)
# Provider: 'groq' (free/cheap, fast) or 'openai'
EXTRACTION_LLM_PROVIDER = 'groq'
EXTRACTION_LLM_MODEL = 'llama-3.1-8b-instant'  # Groq model; for OpenAI use 'gpt-4o-mini'
EXTRACTION_MAX_TEXT_CHARS = 50000  # Truncate long docs to fit context
GROQ_API_KEY = os.environ.get('GROQ_API_KEY')

# Logging: file (back_end/logs/app.log) and console
(BASE_DIR / 'logs').mkdir(exist_ok=True)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': str(BASE_DIR / 'logs' / 'app.log'),
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        'contracts': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
        },
        'civitas': {
            'handlers': ['file'],
            'level': 'INFO',
        },
    },
}

# Log what was loaded for AWS (no secrets) to the same console as runserver / Auth/me / get_or_create_profile
if DEBUG:
    _ak = AWS_ACCESS_KEY_ID or ''
    _ak_masked = (_ak[:4] + '...' + _ak[-2:]) if len(_ak) >= 6 else ('set' if _ak else 'not set')
    import logging
    _log = logging.getLogger('contracts')
    _h = logging.StreamHandler()
    _log.addHandler(_h)
    _log.setLevel(logging.INFO)
    _log.info(
        "AWS config from env: ACCESS_KEY_ID=%s, SECRET_ACCESS_KEY=%s, BUCKET=%s, REGION=%s",
        _ak_masked,
        'set' if AWS_SECRET_ACCESS_KEY else 'not set',
        AWS_STORAGE_BUCKET_NAME or 'not set',
        AWS_REGION,
    )
    _log.removeHandler(_h)
